language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: EG33oHNa+B5FKGArfdmArxGAfg0Fw04FYKH5Oz81dmcFRSOZaTYZnwhYwQryWCD1SFGCuGNe/Uo6kcmRVivPnhlctNiL1z9mq+T/cp3AYHmyY/WJ6q/gTFOCBzxkPww0nJrHKvzbnzCoFH4cv6amTpJB4sWNDjaz/OzDg6vEl3HyTEFGEnKaZFak4aGjW3652PqUqc+mIDK/3Bv6mGc1dproSCBq9ahJ6ijPKPPidl+8yTdJMxA5nQEhG3dx3DheXCrrkM4jv1AP0OZqWVy7bH419pYYg3XyYlbBLAkiRQ4HsFIfDIkfc/0vMsfzXFcR8cixyFkzj9QPMb74k/oTyvQJUuTSSra2c1AYAievnpReGMKm7eG7hYX390X3SwD06ZVeEiDBiqK7i4v7YvhnPVMNrddKWXcZNKg7nL2NhG3kDhaFe+4uIw4ioPx0brxoSV3NSeKLoAzsAJUAx6FS/0lQqt8KLNws5hjIOQWTmQVlM3uOSxJQOJiDvkQfDQ8rVXw7jP9LdcHPxjW7KlK/bH/erOGuUH3kx+P+e7YYPSFApuLAm14vo/qmsaFvug06GvILLSc/bgxz/lZ51IVtFKmB9XPDd8G3RD7nTVVDvcKPxDeoETCr1a0h3afKGlJjTNaEWM1QZGRs8Rvdin7CzvTGr+kgrbQVcS9wSsBgR5M=
  app: juskidin-react
  on:
    repo: reinhal/juskidin-react
